CREATE TABLE TEDARIKCILER(

    tedarikci_id CHAR(5),
    tedarikci_ismi VARCHAR(20),
      tedarikci_adres VARCHAR(20),
    ulasim_tarihi DATE
);

CREATE TABLE tedarikçi_ziyaret

AS  -- VAR OLAN TABLODAN HEADER BASLILARI ALMAK ICIN KOULLANIYORUZ TEKRAR PARANTEZ ACMAYA GEREK YOK.
SELECT tedarikci_ismi,ulasim_tarihi FROM TEDARIKCILER;


SELECT tedarikci_ismi FROM TEDARIKCILER;



CREATE TABLE OGRETMENLER(
kimlik_no CHAR(11),
isim VARCHAR(20),
brans VARCHAR(20),
cinsiyet CHAR(5),
    MAAS REAL
);

INSERT INTO OGRETMENLER  VALUES ('123456789','HASAN','MATEMATIK','ERKEK');


SELECT * FROM OGRETMENLER;

CREATE TABLE OGRETMENLER2(
kimlik_no CHAR(11) PRIMARY KEY,
isim VARCHAR(20) UNIQUE,
brans VARCHAR(20) NOT NULL,
cinsiyet CHAR(5),
    MAAS REAL
);


SELECT * FROM OGRETMENLER2;


INSERT INTO OGRETMENLER2  VALUES ('123456789','HASAN','MATEMATIK','ERKEK',5000);
INSERT INTO OGRETMENLER2  VALUES ('135791111','','MATEMATIK','ERKEK',3000);
INSERT INTO OGRETMENLER2  VALUES ('12345678','NUH','MATEMATIK','ERKEK',5000);
INSERT INTO OGRETMENLER2  VALUES ('123456789','MEHMET','MATEMATIK','ERKEK',8000);

DELETE  FROM OGRETMENLER2;

CREATE TABLE OGRETMENLER4(
kimlik_no CHAR(11) PRIMARY KEY,
isim VARCHAR(20) UNIQUE,
brans VARCHAR(20) NOT NULL,
cinsiyet CHAR(5),
    MAAS REAL
);

SELECT * FROM OGRETMENLER4;

INSERT INTO OGRETMENLER4  VALUES ('123456789','HASAN','MATEMATIK','ERKEK',5000);
INSERT INTO OGRETMENLER4  VALUES ('135791111','',NULL,'ERKEK',3000);
INSERT INTO OGRETMENLER4  VALUES ('12345678','HASAN','MATEMATIK','ERKEK',5000);
INSERT INTO OGRETMENLER4  VALUES ('123456789','MEHMET','MATEMATIK','ERKEK',8000);

CREATE TABLE TEDARIKCILER4
(
tedarikci_id char(10) PRIMARY KEY,
tedarikci_ismi varchar(50),
iletisim_isim varchar(50)
);

CREATE TABLE URUNLER
(
dukkan_id char(10),
urun_id char(10),
CONSTRAINT URUNLERIMIZ FOREIGN KEY (dukkan_id) REFERENCES TEDARIKCILER4 (tedarikci_id)	
);

INSERT INTO TEDARIKCILER4 VALUES ('12345','SELCUK ECZA DEPOSU','IZMIR');
INSERT INTO TEDARIKCILER4 VALUES ('23456','BEZMIALEM','ISTANBUL');
INSERT INTO TEDARIKCILER4 VALUES ('1234567','MEYDAN ECZANE','IZMIT');

SELECT * FROM TEDARIKCILER4;

CREATE TABLE OGRETMENLER5(
kimlik_no CHAR(11) PRIMARY KEY,
isim VARCHAR(20) UNIQUE,
brans VARCHAR(20) NOT NULL,
cinsiyet CHAR(5),
maas REAL CHECK (maas>4000)
);


SELECT * FROM OGRETMENLER5;


INSERT INTO OGRETMENLER5  VALUES ('123456789','HASAN','MATEMATIK','ERKEK',5000);
INSERT INTO OGRETMENLER5  VALUES ('1357910','FATIH','TURKCE','ERKEK',3000);
INSERT INTO OGRETMENLER5  VALUES ('12345678','NUH','MATEMATIK','ERKEK',5000);
INSERT INTO OGRETMENLER5  VALUES ('12345678910','MEHMET','MATEMATIK','ERKEK',8000);


